// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ2ad3pqaYjhs5hTDttn6mwX8yuxBBwlE',
    appId: '1:793067837126:web:05f0b1b51874e2a99f29c7',
    messagingSenderId: '793067837126',
    projectId: 'dodo-booker-10507',
    authDomain: 'dodo-booker-10507.firebaseapp.com',
    storageBucket: 'dodo-booker-10507.firebasestorage.app',
    measurementId: 'G-TG4RNFPXQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB9CfDeL5skfhYhI2InWUk3a-rosw7UL8',
    appId: '1:793067837126:android:04ff7ad0e5ee6df19f29c7',
    messagingSenderId: '793067837126',
    projectId: 'dodo-booker-10507',
    storageBucket: 'dodo-booker-10507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35lV4cITqSQd9dTd47TEHZdkTvCILEu0',
    appId: '1:793067837126:ios:678e655492e617079f29c7',
    messagingSenderId: '793067837126',
    projectId: 'dodo-booker-10507',
    storageBucket: 'dodo-booker-10507.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD35lV4cITqSQd9dTd47TEHZdkTvCILEu0',
    appId: '1:793067837126:ios:678e655492e617079f29c7',
    messagingSenderId: '793067837126',
    projectId: 'dodo-booker-10507',
    storageBucket: 'dodo-booker-10507.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ2ad3pqaYjhs5hTDttn6mwX8yuxBBwlE',
    appId: '1:793067837126:web:8fbb10b043d8b2e79f29c7',
    messagingSenderId: '793067837126',
    projectId: 'dodo-booker-10507',
    authDomain: 'dodo-booker-10507.firebaseapp.com',
    storageBucket: 'dodo-booker-10507.firebasestorage.app',
    measurementId: 'G-X8W80K47LZ',
  );
}
