-- ─────────────────────────────────────────────────────────────────────────────
-- Refund Requests (Tickets)
--
-- Each row represents one customer refund ticket.  A ticket captures the
-- customer's issue, the payment context snapshot, and the admin review
-- decision.  It does NOT represent money movement — that is tracked separately
-- in refund_transactions.
--
-- Ticket lifecycle (status field):
--
--   submitted            Customer (or admin on behalf) raised the ticket.
--   under_review         Admin opened and is actively reviewing.
--   more_info_requested  Admin asked the customer for clarification.
--   approved             Admin approved for a full refund.
--   partially_approved   Admin approved for a partial refund (approved_amount < requested_amount).
--   rejected             Admin rejected the request.
--   processing           At least one refund transaction has been initiated.
--   completed            All approved amount has been fully refunded.
--   failed               The last refund transaction attempt failed; retryable.
--   closed               Terminal state; no further action.
--
-- Transitions enforced by admin_update_refund_status() RPC.
-- ─────────────────────────────────────────────────────────────────────────────

-- Sequence for human-readable ticket numbers: RFD-YYYYMM-NNNNNN
CREATE SEQUENCE IF NOT EXISTS refund_ticket_seq START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS refund_requests (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable ticket number (auto-generated by trigger below).
  ticket_number TEXT NOT NULL UNIQUE,

  -- ── Associations ──────────────────────────────────────────────────────────
  booking_id         UUID NOT NULL REFERENCES bookings(id),
  customer_id        UUID NOT NULL REFERENCES customers(id),

  -- The specific successful payment attempt being refunded.  NULL for
  -- COD/cash bookings where no booking_payments row exists.
  payment_id         UUID REFERENCES booking_payments(id),

  issue_category_id  UUID REFERENCES refund_issue_categories(id),

  -- ── Customer's claim ──────────────────────────────────────────────────────
  description        TEXT,
  requested_amount   NUMERIC(12,2) NOT NULL CHECK (requested_amount > 0),

  -- Stored as a JSON array of public storage URLs.
  -- e.g. ["https://…/refund-evidence/…/photo1.jpg", …]
  evidence_urls      JSONB    NOT NULL DEFAULT '[]'::jsonb,
  evidence_count     SMALLINT NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),

  -- ── Payment context snapshot ──────────────────────────────────────────────
  -- Captured at ticket-creation time so the ticket is self-contained even
  -- if the booking or payment records are later modified.
  payment_method_snapshot  TEXT          NOT NULL
                             CHECK (payment_method_snapshot IN ('online','cash','cod')),
  amount_paid_snapshot     NUMERIC(12,2) NOT NULL CHECK (amount_paid_snapshot >= 0),

  -- ── Ticket lifecycle status ───────────────────────────────────────────────
  status TEXT NOT NULL DEFAULT 'submitted'
    CHECK (status IN (
      'submitted',
      'under_review',
      'more_info_requested',
      'approved',
      'partially_approved',
      'rejected',
      'processing',
      'completed',
      'failed',
      'closed'
    )),

  -- ── Admin review decision ─────────────────────────────────────────────────
  -- Set by admin on approval; NULL until a decision is made.
  approved_amount  NUMERIC(12,2) CHECK (approved_amount > 0 OR approved_amount IS NULL),
  admin_notes      TEXT,
  decision_notes   TEXT,

  -- auth.users.id of the admin who made the review decision.
  reviewed_by  UUID        REFERENCES auth.users(id),
  reviewed_at  TIMESTAMPTZ,

  -- ── Processing summary ────────────────────────────────────────────────────
  -- Denormalised sum of completed refund_transactions.amount for fast display.
  -- Authoritative source of truth is always refund_transactions; this is
  -- updated by fn_sync_refund_processed_amount trigger.
  processed_amount NUMERIC(12,2) NOT NULL DEFAULT 0,

  -- ── Closure ───────────────────────────────────────────────────────────────
  closed_at  TIMESTAMPTZ,
  closed_by  UUID REFERENCES auth.users(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_refund_requests_booking_id
  ON refund_requests (booking_id);

CREATE INDEX IF NOT EXISTS idx_refund_requests_customer_id
  ON refund_requests (customer_id);

CREATE INDEX IF NOT EXISTS idx_refund_requests_status
  ON refund_requests (status);

CREATE INDEX IF NOT EXISTS idx_refund_requests_created_at
  ON refund_requests (created_at DESC);

-- ── Ticket-number generation trigger ─────────────────────────────────────────
-- Format: RFD-YYYYMM-NNNNNN (zero-padded 6-digit sequence)

CREATE OR REPLACE FUNCTION fn_generate_refund_ticket_number()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.ticket_number := 'RFD-'
    || TO_CHAR(NOW(), 'YYYYMM')
    || '-'
    || LPAD(NEXTVAL('refund_ticket_seq')::TEXT, 6, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_refund_requests_ticket_number ON refund_requests;
CREATE TRIGGER trg_refund_requests_ticket_number
  BEFORE INSERT ON refund_requests
  FOR EACH ROW
  WHEN (NEW.ticket_number IS NULL OR NEW.ticket_number = '')
  EXECUTE FUNCTION fn_generate_refund_ticket_number();

-- ── updated_at trigger ────────────────────────────────────────────────────────

DROP TRIGGER IF EXISTS trg_refund_requests_updated_at ON refund_requests;
CREATE TRIGGER trg_refund_requests_updated_at
  BEFORE UPDATE ON refund_requests
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at_subscription();

-- ── RLS ───────────────────────────────────────────────────────────────────────

ALTER TABLE refund_requests ENABLE ROW LEVEL SECURITY;

-- service_role: unrestricted (RPCs run as service_role via SECURITY DEFINER).
DROP POLICY IF EXISTS "service_role_all_refund_requests" ON refund_requests;
CREATE POLICY "service_role_all_refund_requests"
  ON refund_requests FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

-- Admins: full CRUD.
DROP POLICY IF EXISTS "admin_all_refund_requests" ON refund_requests;
CREATE POLICY "admin_all_refund_requests"
  ON refund_requests FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM admin_users
      WHERE admin_users.auth_user_id = auth.uid()
        AND admin_users.is_active = TRUE
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM admin_users
      WHERE admin_users.auth_user_id = auth.uid()
        AND admin_users.is_active = TRUE
    )
  );

-- anon SELECT: future customer app — customer can only see their own tickets.
-- The auth limitation (auth.uid() = NULL for anon customers) is the same
-- constraint that exists on booking_payments.  Row filtering is enforced in
-- Flutter via .eq('customer_id', currentCustomerId).
-- TODO (auth migration): replace USING (true) with customer ownership check.
DROP POLICY IF EXISTS "anon_select_own_refund_requests" ON refund_requests;
CREATE POLICY "anon_select_own_refund_requests"
  ON refund_requests FOR SELECT
  TO anon
  USING (true);

-- anon INSERT: placeholder for future customer-app ticket submission.
-- Intentionally NOT created yet; customer app UI is out of scope for Phase 1.
-- When added, WITH CHECK must validate that booking_id belongs to the customer.
